# Generated by Django 5.1.3 on 2024-11-28 03:08

from django.db import migrations
def insert_initial_questions(apps, schema_editor):
    # Obter o modelo Pergunta
    Pergunta = apps.get_model('api', 'Pergunta')
    
    # Definir as perguntas a serem inseridas
    perguntas = [
        {
            "texto": "Qual é a capital do Brasil?",
            "nivel": "F",
            "alternativa_a": "São Paulo",
            "alternativa_b": "Rio de Janeiro",
            "alternativa_c": "Brasília",
            "alternativa_d": "Salvador",
            "resposta_correta": "C"
        },
        {
            "texto": "Quem foi o primeiro presidente do Brasil?",
            "nivel": "F",
            "alternativa_a": "Getúlio Vargas",
            "alternativa_b": "Juscelino Kubitschek",
            "alternativa_c": "Deodoro da Fonseca",
            "alternativa_d": "Luiz Inácio Lula da Silva",
            "resposta_correta": "C"
        },
        {
            "texto": "Qual é o maior oceano do mundo?",
            "nivel": "M",
            "alternativa_a": "Atlântico",
            "alternativa_b": "Índico",
            "alternativa_c": "Ártico",
            "alternativa_d": "Pacífico",
            "resposta_correta": "D"
        },
        {
            "texto": "Em que ano o homem chegou à Lua?",
            "nivel": "M",
            "alternativa_a": "1969",
            "alternativa_b": "1959",
            "alternativa_c": "1979",
            "alternativa_d": "1989",
            "resposta_correta": "A"
        },
        {
            "texto": "Qual é a fórmula da água?",
            "nivel": "D",
            "alternativa_a": "CO2",
            "alternativa_b": "O2",
            "alternativa_c": "H2O",
            "alternativa_d": "NaCl",
            "resposta_correta": "C"
        },
        {
            "texto": "Qual é o elemento químico mais abundante no universo?",
            "nivel": "D",
            "alternativa_a": "Oxigênio",
            "alternativa_b": "Carbono",
            "alternativa_c": "Hidrogênio",
            "alternativa_d": "Nitrogênio",
            "resposta_correta": "C"
        }
    ]
    
    # Inserir as perguntas no banco de dados
    for pergunta in perguntas:
        Pergunta.objects.create(**pergunta)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_questions),
    ]
